channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.2
  - biopython
  - rdkit==2018.09.2
  - pip:
    - scikit-learn==0.20.3
    - skorch==0.5.0.post0
    - sqlalchemy==1.3.0
    - pg8000==1.13.1
    - docopt==0.6.2
    - pandas==0.24.1
    - jupyter==1.0.0
    - matplotlib==3.0.3
    - dgl==0.2