version: '3'
services:
  idg-dream-db-test:
    image: postgres:9.6
    container_name: idg-dream-db-test
    ports:
     - "${IDG_DREAM_DB_PORT:-6666}:5432"
    environment:
      - POSTGRES_USER=idg_dream
      - POSTGRES_PASSWORD=idg_dream
      - POSTGRES_DB=idg_dream
